CREATE TABLE gmail_mailbox (
    mailbox TEXT PRIMARY KEY,
    history_id NUMERIC(20,0) NOT NULL CHECK (history_id >= 0),
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE gmail_watch (
    mailbox TEXT PRIMARY KEY,
    topic_name TEXT NOT NULL,
    history_id NUMERIC(20,0) NOT NULL CHECK (history_id >= 0),
    expiration_ms BIGINT NOT NULL CHECK (expiration_ms > 0),
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE gmail_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mailbox TEXT NOT NULL,
    pubsub_message_id TEXT NOT NULL UNIQUE,
    history_id NUMERIC(20,0) NOT NULL CHECK (history_id >= 0),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','done')),
    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ,
    UNIQUE (mailbox, history_id)
);
CREATE INDEX gmail_notification_pending ON gmail_notification (mailbox, history_id DESC)
    WHERE status = 'pending';

CREATE TABLE email_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    external_id TEXT NOT NULL,
    thread_id TEXT,
    sender TEXT,
    subject TEXT,
    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL,
    normalized_metadata JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(normalized_metadata) = 'object'),
    UNIQUE (source, external_id)
);
CREATE FUNCTION workflow_reject_email_event_mutation() RETURNS TRIGGER
LANGUAGE plpgsql AS $$ BEGIN
    RAISE EXCEPTION 'email_event is immutable';
END $$;
CREATE TRIGGER email_event_immutable BEFORE UPDATE OR DELETE ON email_event
    FOR EACH ROW EXECUTE FUNCTION workflow_reject_email_event_mutation();

CREATE TABLE extraction_run (
    id TEXT PRIMARY KEY,
    email_event_id BIGINT NOT NULL REFERENCES email_event(id),
    extractor_version TEXT NOT NULL,
    result JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (email_event_id, extractor_version)
);
CREATE TABLE task (
    id TEXT PRIMARY KEY,
    dedupe_key TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    project TEXT NOT NULL,
    priority_score INTEGER NOT NULL,
    priority TEXT NOT NULL,
    owner TEXT,
    due_date DATE,
    status TEXT NOT NULL DEFAULT 'open',
    confidence DOUBLE PRECISION NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE task_source (
    task_id TEXT NOT NULL REFERENCES task(id),
    source TEXT NOT NULL,
    source_key TEXT NOT NULL,
    external_id TEXT NOT NULL,
    PRIMARY KEY (source, source_key),
    UNIQUE (task_id, source, external_id)
);
CREATE TABLE review_queue (
    id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    external_id TEXT NOT NULL,
    candidate_json JSONB NOT NULL,
    reason TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    resolved BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE outbox (
    id TEXT PRIMARY KEY,
    event_key TEXT NOT NULL UNIQUE,
    event_type TEXT NOT NULL,
    payload_json JSONB NOT NULL CHECK (jsonb_typeof(payload_json) = 'object'),
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending','processing','done','dead')),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    created_at TIMESTAMPTZ NOT NULL,
    last_error TEXT,
    lease_owner TEXT,
    lease_until TIMESTAMPTZ,
    CHECK ((lease_owner IS NULL) = (lease_until IS NULL)),
    CHECK (status <> 'processing' OR lease_until IS NOT NULL)
);
CREATE INDEX outbox_claimable ON outbox (created_at, id)
    WHERE status IN ('pending','processing');
CREATE TABLE destination_state (
    task_id TEXT NOT NULL REFERENCES task(id),
    destination TEXT NOT NULL,
    external_object_id TEXT,
    last_synced_version INTEGER NOT NULL DEFAULT 0 CHECK (last_synced_version >= 0),
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (task_id, destination),
    UNIQUE (destination, external_object_id)
);
CREATE TABLE delivery_intent (
    task_id TEXT NOT NULL REFERENCES task(id),
    destination TEXT NOT NULL,
    idempotency_marker TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'creating',
    external_object_id TEXT,
    last_synced_version INTEGER NOT NULL DEFAULT 0 CHECK (last_synced_version >= 0),
    last_error TEXT,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (task_id, destination),
    UNIQUE (destination, idempotency_marker)
);
CREATE TABLE delivery (
    event_id TEXT NOT NULL REFERENCES outbox(id),
    destination TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    external_object_id TEXT,
    last_synced_version INTEGER,
    last_error TEXT,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (event_id, destination)
);
CREATE INDEX delivery_pending ON delivery (destination, status);
CREATE TABLE dead_letter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbox_id TEXT NOT NULL REFERENCES outbox(id),
    destination TEXT NOT NULL,
    reason TEXT NOT NULL,
    attempts INTEGER NOT NULL CHECK (attempts >= 0),
    created_at TIMESTAMPTZ NOT NULL,
    retried_at TIMESTAMPTZ,
    UNIQUE (outbox_id, destination)
);
